# Generated by Django 4.2.7 on 2023-11-13 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_post_body'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
