# Generated by Django 4.2.7 on 2023-12-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_adress_visitorsmodel_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorsmodel',
            name='check_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
